services:

    prometee.payum_stripe_checkout_session.gateway_factory_builder:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        arguments:
            $gatewayFactoryClass: Prometee\PayumStripe\StripeCheckoutSessionGatewayFactory
        tags:
            - { name: payum.gateway_factory_builder, factory: stripe_checkout_session }
