services:

    flux_se.payum_stripe.gateway_factory_builder:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        arguments:
            $gatewayFactoryClass: FluxSE\PayumStripe\StripeCheckoutSessionGatewayFactory
        tags:
            - { name: payum.gateway_factory_builder, factory: stripe_checkout_session }
